version: "3.8"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.scw-fe-test-cert.acme.tlschallenge=true"
      - "--certificatesresolvers.scw-fe-test-cert.acme.email=tsvyatko.ivanov@primeholding.com"
      - "--certificatesresolvers.scw-fe-test-cert.acme.storage=/letsencrypt/acme.json"
      # redirect port 80 -> 443
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`app.temis.ai`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  scw-fe-test:
    image: ghcr.io/tsvyatkoivanov/scw-fe-test
    container_name: "scw-fe-test"
    networks: 
      - traefik-public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.scw-fe-test-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.scw-fe-test.rule=Host(`app.temis.ai`)"
      - "traefik.http.routers.scw-fe-test.entrypoints=web"
      - "traefik.http.routers.scw-fe-test.rule=PathPrefix(`/`)"
      - "traefik.http.routers.scw-fe-test.tls.certresolver=scw-fe-test-cert
      # use compression
      - "traefik.http.routers.scw-fe-test.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"

networks:
  traefik-public:
    external: true