apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scw-fe-test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # tls:
  #   - hosts:
  #       - app.temis.ai
  #     secretName: default-token-5tclp
  rules:
    - host: app.temis.ai
      http:
        paths:
          - path: /staging
            pathType: Prefix
            backend:
              service:
                name: scw-staging-fe-test
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scw-fe-test
                port:
                  number: 80
