apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: scw-fe-test
  environment: fe-prod

namespace: default

images:
  - name: ghcr.io/tsvyatkoivanov/scw-fe-test
    newTag: ag35426

replicas:
  - count: 2
    name: scw-fe-test

resources:
  - deployment.yml
  - service.yml

patchesStrategicMerge:
  - deployment.yml
  - service.yml

images:
  - name: ghcr.io/tsvyatkoivanov/scw-fe-test
    newTag: latest

