apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: scw-fe-test-ingress-router
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app.24bba794-f712-4fb6-92a3-649ad4b9a2b3.nodes.k8s.fr-par.scw.cloud`) && PathPrefix(`/prod`)
      kind: Rule
      services:
        - name: scw-fe-test
          port: 80
    - match: Host(`app.24bba794-f712-4fb6-92a3-649ad4b9a2b3.nodes.k8s.fr-par.scw.cloud`) && PathPrefix(`/staging`)
      kind: Rule
      services:
        - name: scw-staging-fe-test
          port: 80
    -
  tls:
    secretName: scw-fe-test-cert
