apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: scw-test
  environment: dev

resources:
  - deployment.yml
  - ingress.yml
  - service.yml

images:
  - name: ghcr.io/tsvyatkoivanov/scw-test
    newTag: latest
