apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: scwtest
  environment: staging
  namespace: default

resources:
  - deployment.yml
  - ingress.yml
  - service.yml

images:
  - name: ghcr.io/tsvyatkoivanov/scw-test
    newTag: latest
