apiVersion: v1
kind: Service
metadata:
  labels:
    app: scwtest
  name: scwtest
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: scwtest
