# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get commit SHA
        id: get_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image, Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/tsvyatkoivanov/scw-test:${{ steps.get_sha.outputs.sha_short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get commit SHA
        id: get_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Install dependencies
        run: |
          sudo curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.3.0/scw-2.3.0-linux-x86_64"
          sudo chmod +x /usr/local/bin/scw
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          kubectl version --client
          kustomize version
          scw version
      - name: Init SCW
        run: |
          scw init secret-key=${{ secrets.SCW_SECRET_KEY }} send-telemetry=false install-autocomplete=false with-ssh-key=false region=fr-par zone=fr-par-1
      - name: Install kubeconfig
        run: |
          scw k8s kubeconfig install ${{ secrets.SCW_CLUSTER_ID }}
      - name: Deploy new image to staging namespace
        run: |
          sudo ls
          cd k8s
          sudo ls
          cd k8s/overlays
          sudo ls
          cd k8s/overlays/staging
          kustomize edit set image ghcr.io/tsvyatkoivanov/scw-test:${{ steps.get_sha.outputs.sha_short }}
          kustomize build | kubectl apply -f-
      - name: Cleanup
        run: |
          rm -rf /home/runner/.kube/config
          rm -rf /home/runner/.config/scw
