apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scw-fe-test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # tls:
  #   - hosts:
  #       - https://test.24bba794-f712-4fb6-92a3-649ad4b9a2b3.nodes.k8s.fr-par.scw.cloud
  #     secretName: default-token-p7vdn
  rules:
    - host: test-fe.24bba794-f712-4fb6-92a3-649ad4b9a2b3.nodes.k8s.fr-par.scw.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scw-fe-test
                port:
                  number: 80
