apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: scw-staging-fe-test
  environment: fe-staging

namespace: default

images:
  - name: ghcr.io/tsvyatkoivanov/scw-staging-fe-test
    newTag: ag35423

replicas:
  - count: 2
    name: scw-staging-fe-test

resources:
  - deployment.yml
  - service.yml

patchesStrategicMerge:
  - deployment.yml
  - service.yml
  
images:
  - name: ghcr.io/tsvyatkoivanov/scw-staging-fe-test
    newTag: latest

