apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: scwtest
  environment: festaging.

namespace: default

images:
  - name: ghcr.io/tsvyatkoivanov/scw-test
    newTag: latest

replicas:
  - count: 2
    name: scwtest

patchesStrategicMerge:
  - ingress.yml
  - service.yml

resources:
  - ../../base
