apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: scw-fe-test
  environment: fe-staging

namespace: default

images:
  - name: ghcr.io/tsvyatkoivanov/scw-fe-test
    newTag: ag35423

# replicas:
#   - count: 1
#     name: scw-test

patchesStrategicMerge:
  - ingress.yml
  - service.yml

resources:
  - ../../base
