apiVersion: v1
kind: Service
metadata:
  labels:
    app: scw-fe-test
  name: scw-fe-test
spec:
  selector:
    app: scw-fe-test
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
