apiVersion: v1
kind: Service
metadata:
  labels:
    app: scwtest
  name: scwtest
  namespace: default
spec:
  selector:
    app: scwtest
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
